{% set version = "0.4" %}

package:
  name: transformato
  version: {{ version }}

source:
  url: https://github.com/cbc-univie/transformato/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - openmm
    - numpy
    - ipython
    - pymbar
    - rdkit
    - parmed
    - pyyaml
    - mdtraj
    - mdanalysis
    - matplotlib-base
    - networkx
    - tqdm
    - seaborn

test:
  imports:
    - transformato
    - transformato.mutate
    - transformato.analysis
    - transformato.constants
    - transformato.restraints
    - transformato.state
    - transformato.system
    - transformato.utils

about:
  home: https://github.com/wiederm/transformato
  summary: 'Tool for setting up relative binding free energies'
  description: |
    Transformato is a tool that creates files for mutating
    one ligand into another (relative binding free energy).
    The created files are used to run MD simulations and calculate
    the resulting free energy differences.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://cbc-univie.github.io/transformato/

extra:
  recipe-maintainers:
    - wiederm
    - JohannesKarwou
