{% set version = "0.4" %}

package:
  name: transformato
  version: {{ version }}

source:
  url: https://github.com/wiederm/transformato/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 857e136563ad8ed7fc793434d85eb49d01e83b690c1c766c8076110926104a7c

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - openmm
    - numpy
    - ipython
    - pymbar
    - rdkit
    - parmed
    - pyyaml
    - mdtraj
    - mdanalysis
    - matplotlib-base
    - networkx
    - tqdm
    - seaborn


test:
  requires:
    - python {{ python_min }}
  imports:
    - transformato
    - transformato.mutate
    - transformato.analysis
    - transformato.constants
    - transformato.restraints
    - transformato.state
    - transformato.system
    - transformato.utils

about:
  home: https://github.com/wiederm/transformato
  summary: 'Tool for setting up relative binding free energies'
  description: |
    Transformato is a tool that creates files for mutating
    one ligand into another (relative binding free energy).
    The created files are used to run MD simulations and calculate
    the resulting free energy differences.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://wiederm.github.io/transformato/

extra:
  recipe-maintainers:
    - wiederm
    - JohannesKarwou
