{% set version = "0.5" %}

package:
  name: transformato
  version: {{ version }}

source:
  url: https://github.com/wiederm/transformato/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f777e797c1b99825cbf6d74e10ef0c3fcec8eb8d806b9a1ced569b1df60fd017

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    -s setuptools
    - python >=3.6
  run:
    - python >=3.6
    - openmm
    - numpy
    - ipython
    - pymbar
    - rdkit
    - parmed
    - pyyaml
    - mdtraj
    - mdanalysis
    - matplotlib-base
    - networkx
    - tqdm
    - seaborn


test:
  imports:
    - transformato
    - transformato.mutate
    - transformato.analysis
    - transformato.constants
    - transformato.restraints
    - transformato.state
    - transformato.system
    - transformato.utils

about:
  home: https://github.com/wiederm/transformato
  summary: 'Tool for setting up relative binding free energies'
  description: |
    Transformato is a tool that creates files for mutating
    one ligand into another (relative binding free energy).
    The created files are used to run MD simulations and calculate
    the resulting free energy differences.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://wiederm.github.io/transformato/

extra:
  recipe-maintainers:
    - wiederm
    - JohannesKarwou
